name: RegionTP
version: 0.5.2
author: Alterum
main: dev.alterum.regiontp
depend: [WorldGuard]
loadafter: [WorldGuard]
commands:
    regiontp:
        aliases: [sareload, sar]
        description: Main command for the plugin, send users to another region or to specific coordinates.
    spawntp:
        usage: /spawntp (region)
        description: Sends all players in a specific region to a designated spawn point.